name: Deploy Jupyter Notebook as Interactive Dashboard

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notebook voila

    - name: Deploy with Voila
      run: |
        voila "Code/Net. Create Log Data.ipynb" --no-browser --port=8000 --VoilaConfiguration.enable_nbextensions=True &
        sleep 10  # Pause to give Voila time to start

    - name: Upload to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./voila
