name: Deploy Jupyter Notebook as Voila App

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notebook voila

    - name: List files in Code directory (debugging step)
      run: |
        ls -al "Code"

    - name: Convert Notebook to HTML
      run: |
        jupyter nbconvert --to html "Code/Net. Create Log Data.ipynb" --output-dir=./voila_output

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}  # Use the Personal Access Token (PAT)
        publish_dir: ./voila_output
